### PR TITLE
Remove ruff debris when specified

### PR DESCRIPTION
**Pull request by miketheman**

### CODE REVIEW

**Comment by miketheman** [comment]
Hmm, not sure what the test failures are all about.

**Comment by miketheman** [comment]
Looks like it's bombing on trying to upload a coverage report. Are you certain that Pull Requests have access to the token?
https://github.com/bittner/pyclean/blob/d7bbe29481223a8ceb3383062b3793c4b79d02c6/.github/workflows/test.yml#L46

**Comment by bittner** [comment]
Can you please try to rebase your PR? The test should now pass.

**Comment by miketheman** [comment]
Rebased!

**Comment by bittner** [comment]
Still failing, that's odd. It seems like that's how GitHub Repository Secrets work:

> Anyone with collaborator access to this repository can use these secrets and variables for actions. **They are not passed to workflows that are triggered by a pull request from a fork.**

Not sure how I should set up Codacy in GHA other than what I did. :worried: 

The changes look good for me, though. Hence merging! :rocket:

**Review by bittner — APPROVED** [review]

**Comment by bittner** [comment]
Thanks for your contribution! :100:

**Comment by bittner** [comment]
Released v2.7.5 on PyPI, which ships this feature. :heavy_check_mark:

**Pull request merged**
